### ISSUE TITLE
Cleanup repository.

### ISSUE THREAD

**Issue by rl2939** [caluap/jspsych-triple-handle-controller-plugin#3]
## Summary
This is a list of things that I believe we need to complete before we can send a pull request to the jspsych collab repository.

### Todo on the Readme.md:
 Add details to
- [x] Loading
- [x] Compatibility (give a specific version) 
- [x] Author Citations
### Changes to [index.md in the docs folder](https://github.com/caluap/jspsych-triple-handle-controller-plugin/blob/main/docs/index.md):
- [x] Parameters: ~~add file to the~~ Move ["parameters available in all plugins"](https://github.com/caluap/jspsych-triple-handle-controller-plugin/blob/main/overview/plugins.md#parameters-available-in-all-plugins) url to the jspsych web documentation, or delete url
- [x] Data Generated: ~~add file to the~~ Move ["default data collected by all plugins"](https://github.com/caluap/jspsych-triple-handle-controller-plugin/blob/main/overview/plugins.md#data-collected-by-all-plugins) url to the jspsych web documentation, or delete url
- [x] Install: Edit or delete the install section.
- [x] Examples: Remove the text `=== "Code"`
### Other Changes:
- [x] Add Apache License to repository.
- [x] ~~Add CHANGELOG.md to repository.~~ Does not appear to be needed on our end.
